version: '3.9'

name: 'kessing'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    links:
      - database
    networks:
      - kessing

  database:
    image: mariadb:10
    restart: unless-stopped
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kessing

volumes:
  mysql-data:
    driver: local

networks:
  kessing:
