name: Lint

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.yml
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: false
