name: Lint

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.56.0

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.yml
          --ext .js,.jsx,.ts,.tsx
          --fix
        continue-on-error: false

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: false
          yamllint_comment: true
        continue-on-error: false
